import type { Metadata } from 'next';
import './globals.css';
import { geistMono, geistSans, sfProDisplay } from '@/lib/fonts';
import QueryProvider from '@/components/Base/QueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${sfProDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <div className="flex-1 flex flex-col">{children}</div>
        </QueryProvider>
      </body>
    </html>
  );
}
